GET https://isdbsocialmediaserver.skmiraj.online/api/homeposts?page=1
Host: isdbsocialmediaserver.skmiraj.online
Cookie: XSRF-TOKEN=eyJpdiI6ImFjR2YwMXdRVms4TjhPM3F4d1R6dEE9PSIsInZhbHVlIjoidHY0aTJlK1k2UXJ1dEc2STQ0dDh1ajdZMHRYRXByaGVpS2lSOVAyMGtibnBFUFpEdGRTYkpSVFZabStEM0dTYXd5NWIrVmhZYk9OdVhzd0tOTVlwdFZWbzRKSHNSZE1FNnZlZ0w0aDI2ZTMrc3AyeklYaWVzRTc4UG94eU9LelciLCJtYWMiOiIwNDU3Yjk2NWVjNzY3ZjZlZTBhZmQzYTIzY2Y5MmNiMTU5NzZjYmVlZjQ5MmNiZGM3Y2IxMGUwMDkwMjlkY2VmIiwidGFnIjoiIn0%3D; laravel_session=eyJpdiI6IlZubk9FcDRmWWlLYXhsamRpZmlIV1E9PSIsInZhbHVlIjoiNEJJZmw0RHQ3RHB4UTM3NFBUR2xBSzB6THdqMUxXZ3RuNWhqM25BdEVwYW5palhEQWVmREJ4UDRSVGNJTmNrL1ZteWdyaWVOZS9yeG1XK2pFeUI1QVNPMmVjZkpSTXUvYkp2SFdBVTVNdjRwQ0hiRFh0NS91VTVUWHNrdzZzdm4iLCJtYWMiOiIwYTU2NGVjODVlYmQ3ZGU0MTVhZTQ3NDMzNTM1NTRjODk1Y2Y2MTVjNGI0ZGE2N2JlZmZhOGEyMjExYWMyNDY4IiwidGFnIjoiIn0%3D
Origin: : https://isdbsocialmedia.skmiraj.online
Content-Type: application/json

